import { applyMiddleware } from './store/applyMiddleware'
import { createStore } from './store/createStore'
import { thunk } from './store/thunk'
import * as rx from './rx'

export {
  accumulate,
  add,
  addRight,
  aggregate,
  aggregateOn,
  append,
  apply,
  arity,
  average,
  binary,
  bound,
  callFirst,
  callLast,
  compose,
  composeAsync,
  composeM,
  constant,
  curry,
  debounce,
  deepCopy,
  deepEqual,
  deepFreeze,
  deepJoin,
  deepMap,
  deepCopyArray,
  deepPick,
  deepProp,
  deepSetProp,
  demethodize,
  diff,
  divide,
  divideRight,
  entries,
  eq,
  every,
  filter,
  filterAsync,
  filterTR,
  find,
  flat,
  flatMap,
  flip2,
  flip3,
  fold,
  forEach,
  fromJSON,
  FunctionalMixin,
  getOrElseThrow,
  groupBy,
  head,
  identity,
  immutable,
  invert,
  invoke,
  isArray,
  isBoolean,
  isEmpty,
  isFunction,
  isInstanceOf,
  isMap,
  isNull,
  isNumber,
  isObject,
  isSet,
  isString,
  join,
  keyBy,
  keys,
  last,
  len,
  liftA2,
  liftA3,
  liftA4,
  log,
  map,
  mapAsync,
  mapTR,
  match,
  memoize,
  merge,
  multiply,
  multiplyRight,
  not,
  once,
  padEnd,
  padStart,
  parse,
  partition,
  pick,
  pipe,
  pipeAsync,
  pluck,
  pow,
  prepend,
  prop,
  props,
  range,
  reduce,
  reduceAsync,
  reduceRight,
  rename,
  replace,
  roundTo,
  send,
  set,
  setProp,
  setPropM,
  some,
  sortBy,
  split,
  stringify,
  subtract,
  subtractRight,
  sum,
  tap,
  tee,
  ternary,
  toInteger,
  toJSON,
  toLowerCase,
  toString,
  toUpperCase,
  transduce,
  tryCatch,
  unary,
  unique,
  values,
  zipMap,
} from './combinators'
export {
  Enum,
  Failure,
  IO,
  IOAsync,
  Just,
  Maybe,
  Nothing,
  Pair,
  Result,
  Success,
  Triple,
  Try,
  TryAsync,
} from './maybe'
export { createClient } from './fetch'
export {
  compact,
  drop,
  filterWith,
  first,
  mapAllWith,
  mapWith,
  memoizeIter,
  reduceWith,
  rest,
  take,
  untilWith,
  zip,
  zipWith,
} from './iterators'
export {
  after,
  afterAll,
  Append,
  aroundAll,
  before,
  beforeAll,
  ClassMixin,
  Define,
  FactoryFactory,
  Override,
  Prepend,
  provided,
  SubclassFactory,
  unless,
  wrapWith,
} from './classes'

export { Lazy, Collection, Numbers, Stack } from './lazy'
export { Observable } from './rx'
export { rx }
export { EventEmitter, reactivize } from './reactivize'
export { multi, method } from './multimethod'
export { withValidation, ValidationError } from './hofs'
export {
  createFilterStream,
  createFork,
  createMapStream,
  createMerge,
  createReduceStream,
  LimitedParallelStream,
  ParallelStream,
} from './node-streams'
export { actionListener } from './store/actionListener'
export { createAsyncThunk } from './store/asyncThunk'
export { bindActionCreators } from './store/bindActionCreators'
export { combineReducers } from './store/combineReducers'
export { createAction } from './store/createAction'
export { createSelector } from './store/createSelector'
export { isPlainObject } from './store/isPlainObject'
export { Reducer } from './store/reducer'
export { thunk, createStore, applyMiddleware }
export const createConfiguredStore = applyMiddleware(thunk)(createStore)
