import { applyMiddleware } from './store/applyMiddleware.js'
import { createStore } from './store/createStore.js'
import { thunk } from './store/thunk.js'
import * as rx from './rx.js'

export {
  accumulate,
  add,
  addRight,
  aggregate,
  aggregateOn,
  append,
  apply,
  arity,
  average,
  binary,
  bound,
  callFirst,
  callLast,
  compose,
  composeAsync,
  composeM,
  constant,
  curry,
  debounce,
  deepCopy,
  deepEqual,
  deepFreeze,
  deepJoin,
  deepMap,
  deepPick,
  deepProp,
  deepSetProp,
  demethodize,
  diff,
  divide,
  divideRight,
  entries,
  eq,
  every,
  filter,
  filterAsync,
  filterTR,
  find,
  flat,
  flatMap,
  flip2,
  flip3,
  fold,
  forEach,
  fromJSON,
  FunctionalMixin,
  getOrElseThrow,
  groupBy,
  head,
  identity,
  immutable,
  invert,
  invoke,
  isArray,
  isBoolean,
  isEmpty,
  isFunction,
  isInstanceOf,
  isMap,
  isNull,
  isNumber,
  isObject,
  isSet,
  isString,
  join,
  keyBy,
  keys,
  last,
  len,
  liftA2,
  liftA3,
  liftA4,
  log,
  map,
  mapAsync,
  mapTR,
  match,
  memoize,
  merge,
  multiply,
  multiplyRight,
  not,
  once,
  padEnd,
  padStart,
  parse,
  partition,
  pick,
  pipe,
  pipeAsync,
  pluck,
  pow,
  prepend,
  prop,
  props,
  range,
  reduce,
  reduceAsync,
  reduceRight,
  rename,
  replace,
  roundTo,
  send,
  set,
  setProp,
  setPropM,
  some,
  sortBy,
  split,
  stringify,
  subtract,
  subtractRight,
  sum,
  tap,
  tee,
  ternary,
  toInteger,
  toJSON,
  toLowerCase,
  toString,
  toUpperCase,
  transduce,
  tryCatch,
  unary,
  unique,
  values,
  zipMap,
} from './combinators.js'
export {
  Enum,
  Failure,
  IO,
  IOAsync,
  Just,
  Maybe,
  Nothing,
  Pair,
  Result,
  Success,
  Triple,
  Try,
  TryAsync,
} from './maybe.js'
export { createClient } from './fetch.js'
export {
  compact,
  drop,
  filterWith,
  first,
  mapAllWith,
  mapWith,
  memoizeIter,
  reduceWith,
  rest,
  take,
  untilWith,
  zip,
  zipWith,
} from './iterators.js'
export {
  after,
  afterAll,
  Append,
  aroundAll,
  before,
  beforeAll,
  ClassMixin,
  Define,
  FactoryFactory,
  Override,
  Prepend,
  provided,
  SubclassFactory,
  unless,
  wrapWith,
} from './classes.js'

export { Lazy, Collection, Numbers, Stack } from './lazy.js'
export { Observable } from './rx.js'
export { rx }
export { EventEmitter, reactivize } from './reactivize.js'
export { multi, method } from './multimethod.js'
export { withValidation, ValidationError } from './hofs.js'
export {
  createFilterStream,
  createFork,
  createMapStream,
  createMerge,
  createReduceStream,
  LimitedParallelStream,
  ParallelStream,
} from './node-streams.js'
export { actionListener } from './store/actionListener.js'
export { createAsyncThunk } from './store/asyncThunk.js'
export { bindActionCreators } from './store/bindActionCreators.js'
export { combineReducers } from './store/combineReducers.js'
export { createAction } from './store/createAction.js'
export { createSelector } from './store/createSelector.js'
export { isPlainObject } from './store/isPlainObject.js'
export { Reducer } from './store/reducer.js'
export { thunk, createStore, applyMiddleware }
export const createConfiguredStore = applyMiddleware(thunk)(createStore)
