---
name: TypeScript CI
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x, 17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          npm install
          npm run build
          npm run test
        shell: bash
